/**
 * compile-data.ts — Static data pipeline for Myrdl
 * Generates src/data/valid-words.json, src/data/answers.json, src/data/etymology.json
 * Run: npx tsx scripts/compile-data.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = resolve(__dirname, '..')
const dataDir = resolve(projectRoot, 'src', 'data')

// ─── Extract word arrays from wordle-wordlist cache (bypasses module bug) ───

const wordleIndexPath = resolve(projectRoot, 'node_modules', 'wordle-wordlist', 'index.js')
const wordleSource = readFileSync(wordleIndexPath, 'utf8')

const guessesMatch = wordleSource.match(/guessesOnly:\s*(\[.*?\]),\s*\n/s)
const answersMatch = wordleSource.match(/answers:\s*(\[.*?\]),\s*\n/s)

if (!guessesMatch || !answersMatch) {
  console.error('[compile-data] ERROR: Could not parse wordle-wordlist cache')
  process.exit(1)
}

const guessesOnly: string[] = JSON.parse(guessesMatch[1])
const answerWords: string[] = JSON.parse(answersMatch[1])

// ─── valid-words.json: all valid guesses = guessesOnly + answers ─────────────

const allValid = [...new Set([...guessesOnly, ...answerWords].map(w => w.toLowerCase()))]
  .filter(w => w.length === 5 && /^[a-z]+$/.test(w))
  .sort()

console.log(`[compile-data] valid-words: ${allValid.length} entries`)

if (allValid.length < 10000) {
  console.error(`[compile-data] ERROR: valid-words has only ${allValid.length} entries (need >= 10000)`)
  process.exit(1)
}

// ─── answers.json: seeded-shuffle sequence ───────────────────────────────────
//
// Myrdl uses its own deterministic answer sequence — not alphabetical, not
// the original NYT Wordle order. A Fisher-Yates shuffle seeded with a fixed
// Myrdl-specific value produces a stable, non-predictable ordering that is
// consistent forever (same seed always yields the same sequence).
//
// IMPORTANT: Never change MYRDL_ANSWER_SEED after launch. Changing it would
// re-order the entire answer list and invalidate all existing player streaks.

const MYRDL_ANSWER_SEED = 0x4d797264 // 'Myrd' in ASCII hex

function mulberry32(seed: number): () => number {
  let s = seed
  return () => {
    s = (s + 0x6d2b79f5) | 0
    let t = Math.imul(s ^ (s >>> 15), 1 | s)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function seededShuffle(arr: string[], seed: number): string[] {
  const result = [...arr]
  const rand = mulberry32(seed)
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1))
    ;[result[i], result[j]] = [result[j], result[i]]
  }
  return result
}

const validSet = new Set(allValid)
const answers = seededShuffle(
  [...new Set(answerWords.map(w => w.toLowerCase()).filter(w => validSet.has(w)))],
  MYRDL_ANSWER_SEED,
)

console.log(`[compile-data] answers: ${answers.length} entries`)

if (answers.length < 2000) {
  console.error(`[compile-data] ERROR: answers has only ${answers.length} entries (need >= 2000)`)
  process.exit(1)
}

// ─── etymology.json: stub entries for all answer words ───────────────────────

interface EtymologyEntry {
  pos: string
  definition: string
  origin: string
}

// Curated etymology for well-known words
const curatedEtymology: Record<string, EtymologyEntry> = {
  ABACK: { pos: 'adverb', definition: 'Taken by surprise; startled or disconcerted', origin: 'Old English' },
  ABASE: { pos: 'verb', definition: 'To lower in rank, office, prestige, or esteem', origin: 'Old French "abaisser"' },
  ABATE: { pos: 'verb', definition: 'To reduce in amount, degree, or intensity; to lessen', origin: 'Old French "abatre"' },
  ABBEY: { pos: 'noun', definition: 'A monastery or convent governed by an abbot or abbess', origin: 'Old French "abeie", from Latin "abbatia"' },
  ABBOT: { pos: 'noun', definition: 'The head of a monastery or religious community', origin: 'Old English "abbod", from Latin "abbas"' },
  ABHOR: { pos: 'verb', definition: 'To regard with disgust and hatred; to loathe', origin: 'Latin "abhorrere"' },
  ABIDE: { pos: 'verb', definition: 'To accept or tolerate; to remain or continue', origin: 'Old English "abidan"' },
  ABLED: { pos: 'adjective', definition: 'Having a full range of physical and mental capabilities', origin: 'Modern English' },
  ABODE: { pos: 'noun', definition: 'A place of residence; a home or dwelling', origin: 'Old English "abad"' },
  ABORT: { pos: 'verb', definition: 'To bring to a premature end; to terminate', origin: 'Latin "abortare"' },
  ABOUT: { pos: 'preposition', definition: 'On the subject of; concerning; approximately', origin: 'Old English "abutan"' },
  ABOVE: { pos: 'preposition', definition: 'In extended space over; at a higher level or layer than', origin: 'Old English "abufan"' },
  ABUSE: { pos: 'noun/verb', definition: 'Cruel or violent treatment; to use to bad effect', origin: 'Latin "abusus"' },
  ABYSS: { pos: 'noun', definition: 'A deep immeasurable space or cavity; something vast and unknowable', origin: 'Greek "abyssos"' },
  ACUTE: { pos: 'adjective', definition: 'Severe; of short duration but intense; (of an angle) less than 90°', origin: 'Latin "acutus"' },
  ADMIT: { pos: 'verb', definition: 'To confess to be true; to allow entrance to', origin: 'Latin "admittere"' },
  ADOPT: { pos: 'verb', definition: 'To take up or start to use; to legally take another\'s child', origin: 'Latin "adoptare"' },
  ADULT: { pos: 'noun/adjective', definition: 'A fully grown or mature person or organism', origin: 'Latin "adultus"' },
  AFFIX: { pos: 'verb/noun', definition: 'To attach or fasten; a letter or group added to a word', origin: 'Latin "affixus"' },
  AFTER: { pos: 'preposition', definition: 'In the time following; behind in place; in pursuit of', origin: 'Old English "æfter"' },
  AGAIN: { pos: 'adverb', definition: 'Once more; another time; on the other hand', origin: 'Old English "ongean"' },
  AGILE: { pos: 'adjective', definition: 'Able to move quickly and easily; adaptable and resourceful', origin: 'Latin "agilis"' },
  AGONY: { pos: 'noun', definition: 'Extreme physical or mental suffering', origin: 'Greek "agonia"' },
  AGREE: { pos: 'verb', definition: 'To have the same opinion; to consent or concur', origin: 'Old French "agreer"' },
  AHEAD: { pos: 'adverb', definition: 'In or to the front; in advance; further forward in time', origin: 'Old English "aheafod"' },
  AISLE: { pos: 'noun', definition: 'A passage between rows of seats; a side division of a church', origin: 'Old French "ele", from Latin "ala"' },
  ALARM: { pos: 'noun/verb', definition: 'A device that warns of danger; to frighten or disturb', origin: 'Italian "all\'arme" (to arms)' },
  ALBUM: { pos: 'noun', definition: 'A collection of recordings; a blank book for photos or stamps', origin: 'Latin "album" (white tablet)' },
  ALERT: { pos: 'adjective/noun', definition: 'Watchful and prompt to meet danger; a warning signal', origin: 'Italian "all\'erta" (on the watch)' },
  ALIEN: { pos: 'noun/adjective', definition: 'A foreigner; belonging to a foreign country; extraterrestrial', origin: 'Latin "alienus"' },
  ALIGN: { pos: 'verb', definition: 'To place in a straight line; to support a cause or group', origin: 'French "aligner"' },
  ALIKE: { pos: 'adjective/adverb', definition: 'Similar; resembling each other; in the same manner', origin: 'Old English "gelic"' },
  ALIVE: { pos: 'adjective', definition: 'Living; not dead; full of energy or activity', origin: 'Old English "on life"' },
  ALLAY: { pos: 'verb', definition: 'To diminish or put at rest; to lessen or relieve', origin: 'Old English "alecgan"' },
  ALLEY: { pos: 'noun', definition: 'A narrow passageway; a lane used for bowling', origin: 'Old French "alee"' },
  ALLOT: { pos: 'verb', definition: 'To give or apportion by share; to distribute', origin: 'Old French "aloter"' },
  ALLOW: { pos: 'verb', definition: 'To permit; to let have; to acknowledge as valid', origin: 'Old French "alouer"' },
  ALLOY: { pos: 'noun/verb', definition: 'A metal mixture; to mix metals; to debase', origin: 'Old French "aloi"' },
  ALONE: { pos: 'adjective/adverb', definition: 'Without others; solitary; exclusively', origin: 'Middle English "al one" (all one)' },
  ALONG: { pos: 'preposition', definition: 'Moving or extending parallel; in company with', origin: 'Old English "andlang"' },
  ALOOF: { pos: 'adjective/adverb', definition: 'Not friendly or forthcoming; cool and distant', origin: 'Dutch "te loef" (to windward)' },
  ALOUD: { pos: 'adverb', definition: 'Audibly; not silently; using the voice', origin: 'Middle English "on loude"' },
  ALTER: { pos: 'verb', definition: 'To change; to make different; to modify', origin: 'Latin "alterare"' },
  AMAZE: { pos: 'verb', definition: 'To surprise greatly; to fill with wonder or astonishment', origin: 'Old English "amasian"' },
  AMPLE: { pos: 'adjective', definition: 'More than enough; spacious; fully sufficient', origin: 'Latin "amplus"' },
  AMUSE: { pos: 'verb', definition: 'To entertain; to cause to laugh or smile', origin: 'French "amuser"' },
  ANGEL: { pos: 'noun', definition: 'A spiritual being; a very kind person', origin: 'Greek "angelos" (messenger)' },
  ANGRY: { pos: 'adjective', definition: 'Feeling or showing strong annoyance or hostility', origin: 'Old Norse "angr" (grief)' },
  ANKLE: { pos: 'noun', definition: 'The joint connecting the foot with the leg', origin: 'Old English "ancleow"' },
  ANNEX: { pos: 'verb/noun', definition: 'To add as a subordinate part; an addition to a building', origin: 'Latin "annexare"' },
  ANNOY: { pos: 'verb', definition: 'To make slightly angry; to irritate', origin: 'Old French "anoier"' },
  ANTIC: { pos: 'noun/adjective', definition: 'An absurd act intended to amuse; grotesque or bizarre', origin: 'Italian "antico" (antique, grotesque)' },
  APPLE: { pos: 'noun', definition: 'A round fruit with red or green skin and crisp flesh', origin: 'Old English "æppel"' },
  APPLY: { pos: 'verb', definition: 'To put to use; to be relevant; to make a formal request', origin: 'Latin "applicare"' },
  ARDOR: { pos: 'noun', definition: 'Enthusiasm and dedication; great warmth of feeling', origin: 'Latin "ardor"' },
  ARGUE: { pos: 'verb', definition: 'To exchange diverging views; to give reasons for a position', origin: 'Latin "arguere"' },
  ARISE: { pos: 'verb', definition: 'To come into existence; to originate; to get up', origin: 'Old English "arisan"' },
  ARMOR: { pos: 'noun', definition: 'Protective covering worn in combat; metal plating', origin: 'Old French "armure"' },
  AROMA: { pos: 'noun', definition: 'A pleasant smell; a distinctive pervasive quality', origin: 'Greek "aroma" (spice)' },
  ARRAY: { pos: 'noun/verb', definition: 'An ordered arrangement; to arrange in a particular way', origin: 'Old French "areer"' },
  ARSON: { pos: 'noun', definition: 'The criminal act of deliberately setting fire to property', origin: 'Old French "arsion", from Latin "ardere"' },
  ASIDE: { pos: 'adverb/noun', definition: 'To one side; a remark not intended for general hearing', origin: 'Middle English "on side"' },
  ASSET: { pos: 'noun', definition: 'A useful or valuable thing or person; a property owned', origin: 'Old French "asez" (enough)' },
  ATONE: { pos: 'verb', definition: 'To make amends for wrongdoing; to compensate', origin: 'Middle English "at one" (reconcile)' },
  ATTIC: { pos: 'noun', definition: 'A space directly below the roof of a building', origin: 'French "attique", from Greek "Attikos"' },
  AUDIT: { pos: 'noun/verb', definition: 'An official financial examination; to conduct such an examination', origin: 'Latin "auditus" (hearing)' },
  AUGUR: { pos: 'noun/verb', definition: 'A Roman official who interpreted omens; to portend', origin: 'Latin "augur"' },
  AVAIL: { pos: 'verb/noun', definition: 'To help or benefit; usefulness or advantage', origin: 'Old French "valoir"' },
  AVERT: { pos: 'verb', definition: 'To turn away or aside; to prevent from happening', origin: 'Latin "avertere"' },
  AVOID: { pos: 'verb', definition: 'To keep away from; to refrain from; to prevent', origin: 'Old French "esvuidier"' },
  AWAKE: { pos: 'adjective/verb', definition: 'Not asleep; to emerge from or cause to emerge from sleep', origin: 'Old English "awæcnan"' },
  AWARD: { pos: 'noun/verb', definition: 'A prize or honor; to give as a prize or judicial decision', origin: 'Old French "awarder"' },
  AWARE: { pos: 'adjective', definition: 'Having knowledge or perception of a situation or fact', origin: 'Old English "gewær"' },
  AWFUL: { pos: 'adjective', definition: 'Very bad; terrible; inspiring awe', origin: 'Old English "egeful"' },
  BAKER: { pos: 'noun', definition: 'A person who makes and sells bread and cakes', origin: 'Old English "bæcere"' },
  BASIC: { pos: 'adjective/noun', definition: 'Forming an essential foundation; a fundamental fact', origin: 'Latin "basis"' },
  BASIS: { pos: 'noun', definition: 'The underlying support for a principle or idea; a foundation', origin: 'Latin/Greek "basis"' },
  BATCH: { pos: 'noun/verb', definition: 'A quantity produced at one time; to group into sets', origin: 'Old English "bacan"' },
  BEACH: { pos: 'noun', definition: 'A pebbly or sandy shore beside the sea or lake', origin: 'Old English "bece"' },
  BENCH: { pos: 'noun', definition: 'A long seat; a judge\'s seat; a workbench', origin: 'Old English "benc"' },
  BLACK: { pos: 'adjective/noun', definition: 'Of the very darkest color; the absence of light', origin: 'Old English "blæc"' },
  BLADE: { pos: 'noun', definition: 'The flat cutting edge of a knife or sword; a leaf of grass', origin: 'Old English "blæd"' },
  BLAND: { pos: 'adjective', definition: 'Lacking strong features; mild and unremarkable', origin: 'Latin "blandus"' },
  BLAZE: { pos: 'noun/verb', definition: 'A very large or fiercely burning fire; to burn fiercely', origin: 'Old English "blæse"' },
  BLEND: { pos: 'verb/noun', definition: 'To mix together; a mixture of different things', origin: 'Old Norse "blanda"' },
  BLISS: { pos: 'noun', definition: 'Perfect happiness; great joy', origin: 'Old English "bliths"' },
  BLOCK: { pos: 'noun/verb', definition: 'A solid piece of material; to prevent movement or progress', origin: 'Middle Dutch "blocke"' },
  BLOOD: { pos: 'noun', definition: 'The red fluid in the bodies of vertebrate animals', origin: 'Old English "blod"' },
  BLOWN: { pos: 'adjective', definition: 'Past participle of blow; carried by the wind', origin: 'Old English "blawan"' },
  BLUNT: { pos: 'adjective/verb', definition: 'Not having a sharp edge; to make less sharp or intense', origin: 'Middle English "blunt"' },
  BOARD: { pos: 'noun/verb', definition: 'A flat piece of wood; to get on a ship or aircraft', origin: 'Old English "bord"' },
  BONUS: { pos: 'noun', definition: 'Something welcome and often unexpected; extra payment', origin: 'Latin "bonus" (good)' },
  BOXER: { pos: 'noun', definition: 'A person who boxes; a medium-sized dog breed', origin: 'German "Boxer"' },
  BRACE: { pos: 'noun/verb', definition: 'A device that holds things together; to prepare for impact', origin: 'Old French "bracier"' },
  BRAIN: { pos: 'noun', definition: 'The organ in the skull; intellectual capacity', origin: 'Old English "brægen"' },
  BRAVE: { pos: 'adjective', definition: 'Ready to face danger; showing courage', origin: 'Italian "bravo"' },
  BREAD: { pos: 'noun', definition: 'Food made from flour, water, and yeast', origin: 'Old English "bread"' },
  BREAK: { pos: 'verb/noun', definition: 'To separate into pieces; a pause or interruption', origin: 'Old English "brecan"' },
  BREED: { pos: 'verb/noun', definition: 'To produce offspring; a group of animals sharing traits', origin: 'Old English "bredan"' },
  BRIBE: { pos: 'noun/verb', definition: 'Money given to influence; to give such payment', origin: 'Old French "bribe" (lump of bread)' },
  BRIDE: { pos: 'noun', definition: 'A woman on her wedding day', origin: 'Old English "bryd"' },
  BRIEF: { pos: 'adjective/noun', definition: 'Short in duration; a short document or synopsis', origin: 'Old French "bref", from Latin "brevis"' },
  BRISK: { pos: 'adjective', definition: 'Active and energetic; pleasantly cold and fresh', origin: 'Possibly Welsh "brysg"' },
  BROAD: { pos: 'adjective', definition: 'Having a large distance from side to side; wide', origin: 'Old English "brad"' },
  BROWN: { pos: 'adjective/noun', definition: 'A color produced by mixing red, yellow, and black', origin: 'Old English "brun"' },
  BRUSH: { pos: 'noun/verb', definition: 'An implement with bristles; to apply with a brush', origin: 'Old French "brosse"' },
  BUILD: { pos: 'verb', definition: 'To construct by assembling parts; to develop over time', origin: 'Old English "byldan"' },
  BUILT: { pos: 'verb', definition: 'Past tense of build; constructed', origin: 'Old English "byldan"' },
  BUNCH: { pos: 'noun', definition: 'A number of things growing or held together', origin: 'Middle English "bonche"' },
  BURST: { pos: 'verb/noun', definition: 'To break suddenly; a sudden outbreak of activity', origin: 'Old English "berstan"' },
  CABIN: { pos: 'noun', definition: 'A small shelter; a small room on a ship or aircraft', origin: 'Old French "cabane"' },
  CANDY: { pos: 'noun/verb', definition: 'Sweet food made from sugar; to coat with sugar', origin: 'Arabic "qand" (sugar)' },
  CARRY: { pos: 'verb', definition: 'To hold and transport; to conduct; to win', origin: 'Old North French "carier"' },
  CATCH: { pos: 'verb/noun', definition: 'To capture; to intercept; the act of catching', origin: 'Old French "cachier"' },
  CAUSE: { pos: 'noun/verb', definition: 'A reason for an action; to make something happen', origin: 'Latin "causa"' },
  CHAIN: { pos: 'noun/verb', definition: 'Connected metal rings; to fasten with a chain', origin: 'Old French "chaeine"' },
  CHAIR: { pos: 'noun', definition: 'A seat with a back and four legs; a position of authority', origin: 'Old French "chaiere"' },
  CHALK: { pos: 'noun/verb', definition: 'White limestone; to write with chalk', origin: 'Old English "cealc"' },
  CHART: { pos: 'noun/verb', definition: 'A graphical representation; to map or plan', origin: 'French "charte", from Latin "charta"' },
  CHASE: { pos: 'verb/noun', definition: 'To pursue; the act of chasing; a groove or channel', origin: 'Old French "chacier"' },
  CHEAP: { pos: 'adjective', definition: 'Low in price; of poor quality; not valuing enough', origin: 'Old English "ceap" (trade)' },
  CHEAT: { pos: 'verb/noun', definition: 'To act dishonestly; a person who acts dishonestly', origin: 'Middle English "cheten"' },
  CHECK: { pos: 'verb/noun', definition: 'To examine; to control; a pattern of squares', origin: 'Old French "eschec" (chess check)' },
  CHEEK: { pos: 'noun', definition: 'The fleshy part of the face; impudent behavior', origin: 'Old English "ceace"' },
  CHEER: { pos: 'noun/verb', definition: 'A shout of encouragement; to shout in approval', origin: 'Old French "chiere" (face)' },
  CHESS: { pos: 'noun', definition: 'A board game played by two players on a 64-square board', origin: 'Old French "esches", from Persian "shah"' },
  CHILD: { pos: 'noun', definition: 'A young human being; a son or daughter', origin: 'Old English "cild"' },
  CHILL: { pos: 'noun/verb', definition: 'An unpleasant feeling of coldness; to make cold', origin: 'Old English "ciele"' },
  CHINA: { pos: 'noun', definition: 'Fine white ceramic ware; (cap.) a country in East Asia', origin: 'From China, the country' },
  CHUNK: { pos: 'noun', definition: 'A thick, solid piece of something', origin: 'Possibly from "chuck"' },
  CIVIC: { pos: 'adjective', definition: 'Relating to citizens or city; of duties of citizenship', origin: 'Latin "civicus"' },
  CLAIM: { pos: 'verb/noun', definition: 'To assert ownership; to demand; a stated right to something', origin: 'Old French "clamer"' },
  CLASH: { pos: 'verb/noun', definition: 'To come into conflict; a loud sound of impact', origin: 'Imitative origin' },
  CLASP: { pos: 'noun/verb', definition: 'A device for fastening; to grasp tightly', origin: 'Middle English "claspe"' },
  CLEAN: { pos: 'adjective/verb', definition: 'Free from dirt; morally pure; to make free from dirt', origin: 'Old English "clæne"' },
  CLEAR: { pos: 'adjective/verb', definition: 'Transparent; easy to understand; to remove', origin: 'Old French "cler", from Latin "clarus"' },
  CLERK: { pos: 'noun', definition: 'A person who keeps records or does administrative work', origin: 'Old English "cleric"' },
  CLICK: { pos: 'verb/noun', definition: 'To make a sharp sound; a short sharp sound', origin: 'Imitative' },
  CLIFF: { pos: 'noun', definition: 'A steep rock face; a vertical drop', origin: 'Old English "clif"' },
  CLING: { pos: 'verb', definition: 'To hold tightly; to remain attached to', origin: 'Old English "clingan"' },
  CLOCK: { pos: 'noun', definition: 'An instrument for measuring time', origin: 'Middle Dutch "clocke"' },
  CLOSE: { pos: 'verb/adjective', definition: 'To shut; near in space or time; almost equal', origin: 'Old French "clos", from Latin "clausus"' },
  CLOUD: { pos: 'noun', definition: 'A visible mass of water vapor in the atmosphere', origin: 'Old English "clud" (rock)' },
  CLOWN: { pos: 'noun', definition: 'A comic performer; a foolish person', origin: 'Possibly Low German "cluns"' },
  CLUMP: { pos: 'noun/verb', definition: 'A cluster of trees or bushes; to tread heavily', origin: 'Middle Low German "klumpe"' },
  COACH: { pos: 'noun/verb', definition: 'A vehicle; a trainer; to train or instruct', origin: 'French "coche", from Hungarian "kocsi"' },
  COMET: { pos: 'noun', definition: 'A celestial object with a tail that orbits the sun', origin: 'Greek "kometes" (long-haired star)' },
  COMIC: { pos: 'adjective/noun', definition: 'Causing amusement; a comedian; a comic book', origin: 'Latin "comicus"' },
  COUCH: { pos: 'noun/verb', definition: 'A long upholstered seat; to express in words', origin: 'Old French "couche"' },
  CRACK: { pos: 'noun/verb', definition: 'A line of breakage; to break without full separation', origin: 'Old English "cracian"' },
  CRAFT: { pos: 'noun', definition: 'Skill; an occupation requiring skill; a boat or aircraft', origin: 'Old English "cræft"' },
  CRANE: { pos: 'noun/verb', definition: 'A large wading bird; a lifting machine; to stretch the neck', origin: 'Old English "cran"' },
  CRASH: { pos: 'verb/noun', definition: 'To break noisily; a loud breaking sound; a collision', origin: 'Imitative' },
  CREAM: { pos: 'noun', definition: 'The fatty part of milk; a pale yellow-white color', origin: 'Old French "creme"' },
  CREEK: { pos: 'noun', definition: 'A narrow inlet; a small stream', origin: 'Old Norse "kriki"' },
  CREEP: { pos: 'verb/noun', definition: 'To move slowly and quietly; a detestable person', origin: 'Old English "creopan"' },
  CRIME: { pos: 'noun', definition: 'An unlawful act; illegal activity in general', origin: 'Latin "crimen"' },
  CRISP: { pos: 'adjective/noun', definition: 'Firm and brittle; pleasantly fresh; a thin fried slice', origin: 'Old English "crisp"' },
  CROSS: { pos: 'noun/verb/adj', definition: 'A mark or shape; to go across; annoyed', origin: 'Old Norse "kross"' },
  CROWN: { pos: 'noun/verb', definition: 'A ceremonial headdress; to make king or queen', origin: 'Old French "corone"' },
  CRUDE: { pos: 'adjective', definition: 'In a natural or raw state; unrefined; rude', origin: 'Latin "crudus"' },
  CRUEL: { pos: 'adjective', definition: 'Willfully causing pain; harsh and unpleasant', origin: 'Old French "cruel"' },
  CRUMB: { pos: 'noun', definition: 'A small fragment of bread; a worthless person', origin: 'Old English "cruma"' },
  CRUSH: { pos: 'verb/noun', definition: 'To press to extract juice; an infatuation', origin: 'Old French "cruissir"' },
  CRUST: { pos: 'noun', definition: 'The outer layer of bread; the earth\'s surface layer', origin: 'Latin "crusta"' },
  CYCLE: { pos: 'noun/verb', definition: 'A series of events repeated; to ride a bicycle', origin: 'Greek "kyklos" (circle)' },
  DANCE: { pos: 'verb/noun', definition: 'To move rhythmically to music; the activity of dancing', origin: 'Old French "dancier"' },
  DELAY: { pos: 'verb/noun', definition: 'To make late; a period of time by which something is late', origin: 'Old French "delayer"' },
  DENSE: { pos: 'adjective', definition: 'Closely compacted; having high density; stupid', origin: 'Latin "densus"' },
  DEPTH: { pos: 'noun', definition: 'The distance from top to bottom; profundity', origin: 'Old English "deop" (deep)' },
  DEVIL: { pos: 'noun', definition: 'The supreme evil spirit; a very wicked person', origin: 'Old English "deofol"' },
  DIRTY: { pos: 'adjective/verb', definition: 'Not clean; morally wrong; to make dirty', origin: 'Middle English "drit"' },
  DODGE: { pos: 'verb/noun', definition: 'To move aside quickly; a trick to avoid something', origin: 'Unknown origin' },
  DOUBT: { pos: 'noun/verb', definition: 'Uncertainty; to feel uncertain about', origin: 'Old French "douter", from Latin "dubitare"' },
  DOZEN: { pos: 'noun', definition: 'A group or set of twelve', origin: 'Old French "dozaine"' },
  DRAFT: { pos: 'noun/verb', definition: 'A rough version; a current of air; to draw up', origin: 'Old English "dragan"' },
  DRAIN: { pos: 'verb/noun', definition: 'To cause liquid to flow away; a channel for liquid', origin: 'Old English "drehnian"' },
  DRAMA: { pos: 'noun', definition: 'A play; events that are exciting or emotionally charged', origin: 'Greek "drama"' },
  DRAPE: { pos: 'verb/noun', definition: 'To hang loosely; cloth hanging in loose folds', origin: 'Old French "draper"' },
  DRAWN: { pos: 'adjective', definition: 'Past participle of draw; looking strained or tired', origin: 'Old English "dragan"' },
  DREAM: { pos: 'noun/verb', definition: 'Images during sleep; to experience dreams; to imagine', origin: 'Old English "dream" (joy, music)' },
  DRESS: { pos: 'noun/verb', definition: 'A woman\'s garment; to put on clothes; to treat a wound', origin: 'Old French "drecier"' },
  DRIED: { pos: 'adjective', definition: 'Past tense of dry; having had moisture removed', origin: 'Old English "dryge"' },
  DRIFT: { pos: 'verb/noun', definition: 'To be carried along; a heap of snow; a general tendency', origin: 'Old Norse "drift"' },
  DRILL: { pos: 'noun/verb', definition: 'A tool for boring holes; to make a hole; to instruct', origin: 'Middle Dutch "drillen"' },
  DRINK: { pos: 'verb/noun', definition: 'To take liquid into the mouth; any liquid for drinking', origin: 'Old English "drincan"' },
  DRIVE: { pos: 'verb/noun', definition: 'To operate a vehicle; a road; strong motivation', origin: 'Old English "drifan"' },
  DRONE: { pos: 'noun/verb', definition: 'A male bee; an unmanned aircraft; to make a low hum', origin: 'Old English "dran"' },
  DROWN: { pos: 'verb', definition: 'To die or cause to die by submersion in water', origin: 'Old Norse "drukna"' },
  DWARF: { pos: 'noun/verb', definition: 'A mythological small being; to make appear small', origin: 'Old English "dweorg"' },
  EAGER: { pos: 'adjective', definition: 'Keenly enthusiastic or interested', origin: 'Old French "egre", from Latin "acer"' },
  EAGLE: { pos: 'noun', definition: 'A large bird of prey; a golf score of two under par', origin: 'Old French "aigle", from Latin "aquila"' },
  EARLY: { pos: 'adjective/adverb', definition: 'Before the expected time; in the near future', origin: 'Old English "ærlic"' },
  EARTH: { pos: 'noun', definition: 'The planet we live on; soil; the ground', origin: 'Old English "eorthe"' },
  EIGHT: { pos: 'numeral', definition: 'The number 8; one more than seven', origin: 'Old English "eahta"' },
  ELBOW: { pos: 'noun/verb', definition: 'The joint of the arm; to push with the elbow', origin: 'Old English "elnboga"' },
  ELDER: { pos: 'noun/adjective', definition: 'An older person; of greater age; a berry-bearing tree', origin: 'Old English "eald" (old)' },
  EMPTY: { pos: 'adjective/verb', definition: 'Containing nothing; to remove contents from', origin: 'Old English "æmtig"' },
  ENEMY: { pos: 'noun', definition: 'A person who is actively hostile to another; an opponent', origin: 'Old French "enemi", from Latin "inimicus"' },
  ENTRY: { pos: 'noun', definition: 'An act of going in; a record in a list; a doorway', origin: 'Old French "entree"' },
  ENVOY: { pos: 'noun', definition: 'A messenger; a diplomatic representative', origin: 'French "envoyé"' },
  EQUAL: { pos: 'adjective/verb', definition: 'The same in quantity or quality; to be the same as', origin: 'Latin "aequalis"' },
  ERODE: { pos: 'verb', definition: 'To gradually wear away; to diminish or destroy', origin: 'Latin "erodere"' },
  EVADE: { pos: 'verb', definition: 'To escape by cleverness; to avoid dealing with', origin: 'Latin "evadere"' },
  EVENT: { pos: 'noun', definition: 'A thing that happens; an organized occasion', origin: 'Latin "eventus"' },
  EVERY: { pos: 'adjective/adverb', definition: 'All the individual members of a set; used to indicate frequency', origin: 'Old English "æfre ælc"' },
  EXACT: { pos: 'adjective/verb', definition: 'Completely accurate; to demand and obtain', origin: 'Latin "exactus"' },
  EXTRA: { pos: 'adjective/noun', definition: 'More than is needed; something additional', origin: 'Latin "extra" (outside)' },
  FAINT: { pos: 'adjective/verb', definition: 'Lacking strength; to lose consciousness briefly', origin: 'Old French "feint"' },
  FAIRY: { pos: 'noun', definition: 'A small imaginary being with magical powers', origin: 'Old French "faerie"' },
  FAITH: { pos: 'noun', definition: 'Complete trust; a strong belief; a religion', origin: 'Old French "feid", from Latin "fides"' },
  FALSE: { pos: 'adjective', definition: 'Not correct; disloyal; not genuine', origin: 'Old English "fals", from Latin "falsus"' },
  FANCY: { pos: 'adjective/noun/verb', definition: 'Elaborate; a desire or whim; to feel attracted to', origin: 'Middle English "fantasie"' },
  FATAL: { pos: 'adjective', definition: 'Causing death; having disastrous consequences', origin: 'Latin "fatalis"' },
  FEAST: { pos: 'noun/verb', definition: 'A large elaborate meal; to eat richly', origin: 'Old French "feste"' },
  FENCE: { pos: 'noun/verb', definition: 'A barrier; to enclose with a fence; to practice fencing', origin: 'Middle English "fens"' },
  FETCH: { pos: 'verb', definition: 'To go and get; to bring back; to sell for a price', origin: 'Old English "feccan"' },
  FIELD: { pos: 'noun/verb', definition: 'An area of open land; to deal with questions', origin: 'Old English "feld"' },
  FIGHT: { pos: 'verb/noun', definition: 'To take part in combat; a violent confrontation', origin: 'Old English "feohtan"' },
  FINAL: { pos: 'adjective/noun', definition: 'Last; coming at the end; a decisive contest', origin: 'Old French "final"' },
  FIRST: { pos: 'adjective/adverb', definition: 'Preceding all others; before anything else', origin: 'Old English "fyrest"' },
  FIXED: { pos: 'adjective', definition: 'Fastened securely; not changing; arranged dishonestly', origin: 'Latin "fixus"' },
  FLAME: { pos: 'noun/verb', definition: 'A hot bright stream of burning gas; to burn with a flame', origin: 'Old French "flambe"' },
  FLASH: { pos: 'noun/verb', definition: 'A sudden brief blaze of light; to shine briefly', origin: 'Imitative' },
  FLASK: { pos: 'noun', definition: 'A container with a narrow neck for liquid', origin: 'Medieval Latin "flasca"' },
  FLOCK: { pos: 'noun/verb', definition: 'A group of birds or sheep; to gather in large numbers', origin: 'Old English "flocc"' },
  FLOOD: { pos: 'noun/verb', definition: 'An overflow of water onto land; to cover with water', origin: 'Old English "flod"' },
  FLOUR: { pos: 'noun', definition: 'Finely ground grain used in baking', origin: 'Variant of "flower" (the finest part)' },
  FLUID: { pos: 'noun/adjective', definition: 'A substance that flows; not fixed or settled', origin: 'Latin "fluidus"' },
  FLUSH: { pos: 'adjective/verb', definition: 'Level; to cause water to flow through; to redden', origin: 'Possibly from "flash"' },
  FOCAL: { pos: 'adjective', definition: 'Relating to a focus; of central importance', origin: 'Latin "focus" (hearth)' },
  FORCE: { pos: 'noun/verb', definition: 'Strength or power; to compel; to push against', origin: 'Old French "force"' },
  FORGE: { pos: 'noun/verb', definition: 'A blacksmith\'s furnace; to form by heating; to counterfeit', origin: 'Old French "forge"' },
  FORTH: { pos: 'adverb', definition: 'Out and away; forward; so as to be visible', origin: 'Old English "forth"' },
  FOUND: { pos: 'verb', definition: 'Past tense of find; to establish or set up', origin: 'Old French "fonder"' },
  FRAME: { pos: 'noun/verb', definition: 'A rigid structure; to construct; to formulate', origin: 'Old English "framian"' },
  FRESH: { pos: 'adjective', definition: 'Not stale; recently made; full of energy', origin: 'Old English "fersc"' },
  FROST: { pos: 'noun/verb', definition: 'Frozen dew; to cover with frost or icing', origin: 'Old English "forst"' },
  FROZE: { pos: 'verb', definition: 'Past tense of freeze', origin: 'Old English "freosan"' },
  FRUIT: { pos: 'noun', definition: 'The sweet product of a plant; the result of work', origin: 'Old French "fruit", from Latin "fructus"' },
  FULLY: { pos: 'adverb', definition: 'Completely; entirely; to the greatest extent', origin: 'Old English "fullice"' },
  FUZZY: { pos: 'adjective', definition: 'Having a frizzy texture; not clear; blurred', origin: 'Possibly Low German "fussig"' },
  GAUGE: { pos: 'noun/verb', definition: 'A measuring instrument; to measure; to assess', origin: 'Old French "gauge"' },
  GIVEN: { pos: 'adjective/noun', definition: 'Specified; assumed; a thing that is accepted as true', origin: 'Old English "giefan"' },
  GLASS: { pos: 'noun', definition: 'A hard transparent material; a drinking vessel', origin: 'Old English "glæs"' },
  GLOBE: { pos: 'noun', definition: 'A spherical representation of the earth; the world', origin: 'Latin "globus"' },
  GLOOM: { pos: 'noun', definition: 'Partial or total darkness; depression', origin: 'Middle English "gloumen"' },
  GLOVE: { pos: 'noun', definition: 'A covering for the hand with separate finger sections', origin: 'Old English "glof"' },
  GOING: { pos: 'noun/adjective', definition: 'An instance of going; conditions for progress', origin: 'Old English "gan"' },
  GORGE: { pos: 'noun/verb', definition: 'A narrow valley; to eat until full', origin: 'Old French "gorge" (throat)' },
  GOURD: { pos: 'noun', definition: 'A large fleshy fruit; its hard shell used as a container', origin: 'Old French "gourde"' },
  GRACE: { pos: 'noun/verb', definition: 'Elegance; divine favor; to honor with presence', origin: 'Old French "grace", from Latin "gratia"' },
  GRADE: { pos: 'noun/verb', definition: 'A level or rank; to arrange in grades; to assess', origin: 'Latin "gradus"' },
  GRAIN: { pos: 'noun', definition: 'Seeds of cereal plants; a tiny particle; texture of wood', origin: 'Old French "grain", from Latin "granum"' },
  GRANT: { pos: 'verb/noun', definition: 'To agree to give; a sum of money given by an organization', origin: 'Old French "granter"' },
  GRASP: { pos: 'verb/noun', definition: 'To seize firmly; a firm grip; understanding', origin: 'Middle English "graspen"' },
  GRATE: { pos: 'verb/noun', definition: 'To shred food; to irritate; a framework of bars', origin: 'Old French "grater"' },
  GRAZE: { pos: 'verb/noun', definition: 'To eat grass; to scrape lightly; a slight wound', origin: 'Old English "grasian"' },
  GREED: { pos: 'noun', definition: 'Intense desire for wealth or food; avarice', origin: 'Old English "grædig"' },
  GREEN: { pos: 'adjective/noun', definition: 'The color of grass; inexperienced; an area of grass', origin: 'Old English "grene"' },
  GRIEF: { pos: 'noun', definition: 'Deep sorrow; intense mental suffering', origin: 'Old French "grief"' },
  GRIME: { pos: 'noun', definition: 'Dirt ingrained in a surface', origin: 'Flemish "grijm"' },
  GRIND: { pos: 'verb/noun', definition: 'To reduce to powder; hard tedious work', origin: 'Old English "grindan"' },
  GROAN: { pos: 'verb/noun', definition: 'To make a low sound of pain; such a sound', origin: 'Old English "granian"' },
  GROSS: { pos: 'adjective/noun', definition: 'Unpleasant; a total before deductions; 144 items', origin: 'Old French "gros" (large)' },
  GROVE: { pos: 'noun', definition: 'A small wood; a group of trees', origin: 'Old English "graf"' },
  GROWN: { pos: 'adjective', definition: 'Past participle of grow; fully developed', origin: 'Old English "growan"' },
  GUEST: { pos: 'noun', definition: 'A person invited to visit; a person staying at a hotel', origin: 'Old Norse "gestr"' },
  GUIDE: { pos: 'noun/verb', definition: 'One who shows the way; to direct or show the way', origin: 'Old French "guider"' },
  GUILT: { pos: 'noun', definition: 'The fact of having committed a wrong; a feeling of remorse', origin: 'Old English "gylt"' },
  GUISE: { pos: 'noun', definition: 'An outward appearance; a false front', origin: 'Old French "guise"' },
  HABIT: { pos: 'noun', definition: 'A settled tendency; a monk\'s garment; an addiction', origin: 'Old French "habit", from Latin "habitus"' },
  HARSH: { pos: 'adjective', definition: 'Unpleasantly rough; cruel; severe', origin: 'Middle Low German "harsch"' },
  HASTY: { pos: 'adjective', definition: 'Done too quickly; hurried; rash', origin: 'Old French "haste"' },
  HAUNT: { pos: 'verb/noun', definition: 'To frequent as a ghost; to preoccupy; a favorite place', origin: 'Old French "hanter"' },
  HAVEN: { pos: 'noun', definition: 'A place of safety; a harbor', origin: 'Old English "hæfen"' },
  HEDGE: { pos: 'noun/verb', definition: 'A boundary of shrubs; to limit a risk; to be evasive', origin: 'Old English "hecg"' },
  HEIST: { pos: 'noun', definition: 'A robbery; a theft', origin: 'Dialectal variant of "hoist"' },
  HINGE: { pos: 'noun/verb', definition: 'A movable joint on a door; to attach by hinges; to depend on', origin: 'Middle English "henge"' },
  HIPPO: { pos: 'noun', definition: 'A hippopotamus; a large African mammal', origin: 'Greek "hippopotamos" (horse of the river)' },
  HITCH: { pos: 'verb/noun', definition: 'To move jerkily; to fasten temporarily; a problem', origin: 'Unknown origin' },
  HOIST: { pos: 'verb/noun', definition: 'To lift using ropes; an apparatus for hoisting', origin: 'Low German "hissen"' },
  HONEY: { pos: 'noun', definition: 'A sweet substance made by bees; a term of endearment', origin: 'Old English "hunig"' },
  HOTEL: { pos: 'noun', definition: 'An establishment providing paid accommodation', origin: 'French "hôtel", from Latin "hospitale"' },
  HOUND: { pos: 'noun/verb', definition: 'A hunting dog; to pursue relentlessly', origin: 'Old English "hund"' },
  HOVER: { pos: 'verb', definition: 'To remain in one place in the air; to wait nearby', origin: 'Middle English "hoveren"' },
  HUMID: { pos: 'adjective', definition: 'Having a high degree of moisture in the air', origin: 'Latin "humidus"' },
  HURRY: { pos: 'verb/noun', definition: 'To move or act quickly; urgent action', origin: 'Possibly imitative' },
  IDEAL: { pos: 'noun/adjective', definition: 'A perfect standard; satisfying ideal conditions', origin: 'Latin "idealis"' },
  IMPLY: { pos: 'verb', definition: 'To suggest without stating directly; to hint', origin: 'Latin "implicare"' },
  INERT: { pos: 'adjective', definition: 'Lacking the ability to move; chemically inactive', origin: 'Latin "iners" (idle)' },
  INNER: { pos: 'adjective', definition: 'Inside; relating to the mind or spirit; private', origin: 'Old English "innera"' },
  IRONY: { pos: 'noun', definition: 'The expression of meaning opposite to the literal; a paradox', origin: 'Greek "eironeia" (feigned ignorance)' },
  JAZZY: { pos: 'adjective', definition: 'Bright and showy; resembling jazz music', origin: 'From "jazz"' },
  JOUST: { pos: 'verb/noun', definition: 'To engage in a jousting tournament; a tournament fight', origin: 'Old French "joster"' },
  JUICE: { pos: 'noun', definition: 'The liquid in fruit; electricity; vigor', origin: 'Old French "jus"' },
  JUMBO: { pos: 'adjective/noun', definition: 'Very large; a very large person or thing', origin: 'From Jumbo, a famous elephant' },
  KAYAK: { pos: 'noun', definition: 'A small covered canoe propelled by a double-bladed paddle', origin: 'Inuit "qayaq"' },
  KHAKI: { pos: 'adjective/noun', definition: 'A dull brownish-yellow color; fabric of this color', origin: 'Urdu "khaki" (dusty)' },
  KNACK: { pos: 'noun', definition: 'An acquired skill; a tendency to do something', origin: 'Middle Dutch "cnac"' },
  KNEEL: { pos: 'verb', definition: 'To go down on one or both knees', origin: 'Old English "cneowlian"' },
  KNIFE: { pos: 'noun/verb', definition: 'A cutting instrument with a blade; to cut with a knife', origin: 'Old Norse "knifr"' },
  KNOCK: { pos: 'verb/noun', definition: 'To strike a surface; a sound made by striking', origin: 'Old English "cnocian"' },
  KNOLL: { pos: 'noun', definition: 'A small hill or mound', origin: 'Old English "cnoll"' },
  KNOWN: { pos: 'adjective', definition: 'Past participle of know; recognized; familiar', origin: 'Old English "cnawan"' },
  LABEL: { pos: 'noun/verb', definition: 'A piece of paper giving information; to attach a label', origin: 'Old French "label"' },
  LANCE: { pos: 'noun/verb', definition: 'A long weapon; a surgical needle; to pierce with a lance', origin: 'Old French "lance"' },
  LARGE: { pos: 'adjective', definition: 'Of considerable size; extensive', origin: 'Old French "large"' },
  LASER: { pos: 'noun', definition: 'A device that emits a narrow intense beam of light', origin: 'Acronym: Light Amplification by Stimulated Emission of Radiation' },
  LATCH: { pos: 'noun/verb', definition: 'A bar that holds a door closed; to fasten with a latch', origin: 'Old English "læccan"' },
  LATTE: { pos: 'noun', definition: 'A coffee drink made with espresso and steamed milk', origin: 'Italian "caffè latte" (milk coffee)' },
  LAYER: { pos: 'noun/verb', definition: 'A sheet or quantity of material; to arrange in layers', origin: 'Old English "lecgan"' },
  LEARN: { pos: 'verb', definition: 'To gain knowledge or skill; to find out about', origin: 'Old English "leornian"' },
  LEGAL: { pos: 'adjective', definition: 'Permitted by law; relating to the law', origin: 'Latin "legalis"' },
  LEVEL: { pos: 'noun/adjective/verb', definition: 'A horizontal plane; flat and even; to make flat', origin: 'Old French "livel"' },
  LEMON: { pos: 'noun', definition: 'A yellow citrus fruit; a pale yellow color', origin: 'Arabic "laymun"' },
  LIGHT: { pos: 'noun/adjective', definition: 'Electromagnetic radiation visible to the eye; not heavy', origin: 'Old English "leoht"' },
  LIMIT: { pos: 'noun/verb', definition: 'A point beyond which something cannot go; to restrict', origin: 'Latin "limes" (boundary)' },
  LINEN: { pos: 'noun', definition: 'Cloth woven from flax; household items made from cloth', origin: 'Old English "linen"' },
  LINER: { pos: 'noun', definition: 'A large passenger ship; something used to line another', origin: 'From "line"' },
  LOCAL: { pos: 'adjective/noun', definition: 'Relating to a particular area; a person from the area', origin: 'Latin "localis"' },
  LOGIC: { pos: 'noun', definition: 'Reasoning conducted according to strict rules of validity', origin: 'Greek "logike"' },
  LOYAL: { pos: 'adjective', definition: 'Giving firm and constant support; faithful', origin: 'Old French "loial", from Latin "legalis"' },
  LUCID: { pos: 'adjective', definition: 'Expressed clearly; not confused; translucent', origin: 'Latin "lucidus"' },
  LUCKY: { pos: 'adjective', definition: 'Having or resulting from good luck; fortunate', origin: 'Middle Dutch "luc"' },
  LUMPY: { pos: 'adjective', definition: 'Full of lumps; not smooth', origin: 'Middle English "lompe"' },
  LYRIC: { pos: 'adjective/noun', definition: 'Expressing personal emotion; words of a song', origin: 'Greek "lyrikos"' },
  MAGIC: { pos: 'noun/adjective', definition: 'The power of apparently influencing events supernaturally', origin: 'Greek "magike"' },
  MAKER: { pos: 'noun', definition: 'A person or thing that makes something', origin: 'Old English "macian"' },
  MANOR: { pos: 'noun', definition: 'A large country house; a feudal estate', origin: 'Old French "manoir"' },
  MARCH: { pos: 'noun/verb', definition: 'The third month; to walk in a military manner', origin: 'Old French "marche"' },
  MAYOR: { pos: 'noun', definition: 'The elected head of a city or town', origin: 'Old French "maire"' },
  MEDAL: { pos: 'noun', definition: 'A metal disc awarded for achievement or bravery', origin: 'French "médaille"' },
  MERIT: { pos: 'noun/verb', definition: 'Excellence; the quality of deserving reward; to deserve', origin: 'Latin "meritum"' },
  METAL: { pos: 'noun', definition: 'A hard shiny material; a genre of loud rock music', origin: 'Old French "metal", from Latin "metallum"' },
  MIGHT: { pos: 'modal verb/noun', definition: 'Expressing possibility; great power or strength', origin: 'Old English "miht"' },
  MINER: { pos: 'noun', definition: 'A person who works in a mine', origin: 'Old French "mineur"' },
  MINOR: { pos: 'adjective/noun', definition: 'Lesser; not very important; a person under legal age', origin: 'Latin "minor"' },
  MINUS: { pos: 'preposition/noun', definition: 'With the subtraction of; a disadvantage', origin: 'Latin "minus"' },
  MIRTH: { pos: 'noun', definition: 'Amusement; laughter; being merry', origin: 'Old English "myrgth"' },
  MOIST: { pos: 'adjective', definition: 'Slightly wet; damp', origin: 'Old French "moiste"' },
  MONEY: { pos: 'noun', definition: 'A medium of exchange; coins and banknotes', origin: 'Old French "moneie", from Latin "moneta"' },
  MONTH: { pos: 'noun', definition: 'Any of the twelve periods into which a year is divided', origin: 'Old English "monath"' },
  MORAL: { pos: 'adjective/noun', definition: 'Concerned with right and wrong; a lesson from a story', origin: 'Latin "moralis"' },
  MUDDY: { pos: 'adjective/verb', definition: 'Covered in or resembling mud; to make unclear', origin: 'Middle English "mudde"' },
  MULCH: { pos: 'noun/verb', definition: 'Material spread to protect soil; to cover with mulch', origin: 'German "molsch" (soft)' },
  MURAL: { pos: 'noun/adjective', definition: 'A painting on a wall; relating to a wall', origin: 'Latin "muralis"' },
  MUSTY: { pos: 'adjective', definition: 'Having a stale smell; out of date', origin: 'Possibly from "moist"' },
  NAVAL: { pos: 'adjective', definition: 'Of or relating to a navy or warships', origin: 'Latin "navalis"' },
  NIGHT: { pos: 'noun', definition: 'The period between sunset and sunrise; darkness', origin: 'Old English "niht"' },
  NOBLE: { pos: 'adjective/noun', definition: 'Of high moral character; a person of high rank', origin: 'Latin "nobilis"' },
  NOISE: { pos: 'noun', definition: 'A sound; a loud or unwanted sound', origin: 'Old French "noise"' },
  NORTH: { pos: 'noun/adjective', definition: 'The direction opposite south; the northern part', origin: 'Old English "north"' },
  NOTCH: { pos: 'noun/verb', definition: 'A V-shaped cut; to cut a notch in', origin: 'Old French "oche"' },
  NOVEL: { pos: 'noun/adjective', definition: 'A long work of fiction; new and original', origin: 'Italian "novella"' },
  NUDGE: { pos: 'verb/noun', definition: 'To push gently; a gentle push', origin: 'Possibly Norwegian "nugge" (to push)' },
  NURSE: { pos: 'noun/verb', definition: 'A person trained to care for the sick; to care for', origin: 'Old French "norrice"' },
  NYMPH: { pos: 'noun', definition: 'A mythological spirit of nature; a larva of certain insects', origin: 'Greek "nymphe"' },
  OCCUR: { pos: 'verb', definition: 'To happen; to be found; to come to mind', origin: 'Latin "occurrere"' },
  OCTET: { pos: 'noun', definition: 'A group of eight; a musical composition for eight performers', origin: 'Latin "octo" (eight)' },
  OPINE: { pos: 'verb', definition: 'To hold or state an opinion; to assert', origin: 'Latin "opinari"' },
  OPTIC: { pos: 'adjective/noun', definition: 'Relating to the eye or vision; a nerve or lens', origin: 'Greek "optikos"' },
  OXIDE: { pos: 'noun', definition: 'A compound of oxygen with another element', origin: 'French "oxyde"' },
  OZONE: { pos: 'noun', definition: 'A form of oxygen with a pungent smell; the atmosphere', origin: 'Greek "ozein" (to smell)' },
  PAINT: { pos: 'noun/verb', definition: 'A colored substance; to apply paint; to describe vividly', origin: 'Old French "peindre"' },
  PANIC: { pos: 'noun/verb', definition: 'Sudden uncontrollable fear; to feel such fear', origin: 'Greek "panikon" (from Pan, Greek god)' },
  PAUSE: { pos: 'noun/verb', definition: 'A temporary stop; to stop temporarily', origin: 'Greek "pausis"' },
  PEACH: { pos: 'noun', definition: 'A fruit with fuzzy skin; a pale orange-pink color', origin: 'Old French "pesche"' },
  PEARL: { pos: 'noun', definition: 'A hard lustrous gem formed in oysters; something precious', origin: 'Old French "perle"' },
  PERCH: { pos: 'noun/verb', definition: 'A freshwater fish; a branch as resting place; to sit on', origin: 'Old French "perche"' },
  PERKY: { pos: 'adjective', definition: 'Cheerful and lively; confidently self-assertive', origin: 'Unknown origin' },
  PETTY: { pos: 'adjective', definition: 'Of little importance; small-minded; minor in rank', origin: 'Old French "petit"' },
  PHASE: { pos: 'noun/verb', definition: 'A stage in a process; to carry out in stages', origin: 'Greek "phasis"' },
  PHONE: { pos: 'noun/verb', definition: 'A telephone; to call on the telephone', origin: 'Greek "phone" (sound, voice)' },
  PHOTO: { pos: 'noun', definition: 'A photograph; an image captured by a camera', origin: 'Greek "photos" (light)' },
  PIANO: { pos: 'noun/adjective', definition: 'A keyboard instrument; softly (in music)', origin: 'Italian "pianoforte"' },
  PILOT: { pos: 'noun/verb', definition: 'A person who flies an aircraft; to navigate; a test', origin: 'French "pilote"' },
  PINCH: { pos: 'verb/noun', definition: 'To squeeze between finger and thumb; a small amount', origin: 'Old French "pincier"' },
  PIXEL: { pos: 'noun', definition: 'The smallest element of a digital image', origin: 'Portmanteau of "picture element"' },
  PIZZA: { pos: 'noun', definition: 'An Italian dish with a flat dough base and toppings', origin: 'Italian "pizza"' },
  PLANT: { pos: 'noun/verb', definition: 'A living organism with roots; to put in the ground', origin: 'Old English "plante"' },
  PLATE: { pos: 'noun/verb', definition: 'A flat dish; a flat piece of metal; to coat with metal', origin: 'Old French "plate"' },
  PLAZA: { pos: 'noun', definition: 'A public square; a shopping center', origin: 'Spanish "plaza"' },
  PLUCK: { pos: 'verb/noun', definition: 'To pull quickly; courage; the edible organs of an animal', origin: 'Old English "ploccian"' },
  PLUME: { pos: 'noun/verb', definition: 'A long feather; to pride oneself; to rise in a column', origin: 'Old French "plume"' },
  PLUMP: { pos: 'adjective/verb', definition: 'Slightly fat; to put down heavily; to increase fullness', origin: 'Middle Dutch "plomp" (blunt)' },
  POACH: { pos: 'verb', definition: 'To cook in gently simmering water; to steal game', origin: 'Old French "pochier"' },
  POKER: { pos: 'noun', definition: 'A card game; a metal rod for stirring fire', origin: 'Dutch "poker"' },
  POLKA: { pos: 'noun', definition: 'A lively dance of Bohemian origin', origin: 'Czech "pulka" (half-step)' },
  POUCH: { pos: 'noun', definition: 'A small bag; a marsupial\'s abdominal pouch', origin: 'Old French "poche"' },
  POUND: { pos: 'noun/verb', definition: 'A unit of weight; the British currency; to strike heavily', origin: 'Old English "pund"' },
  POWER: { pos: 'noun', definition: 'The ability to do something; authority; electricity supply', origin: 'Old French "poer"' },
  PRANK: { pos: 'noun', definition: 'A practical joke; a mischievous act', origin: 'Possibly Dutch "pronk" (show)' },
  PRESS: { pos: 'verb/noun', definition: 'To push; to iron; newspapers collectively; a machine', origin: 'Old French "presser"' },
  PRICE: { pos: 'noun/verb', definition: 'The amount paid for something; to set a price on', origin: 'Old French "pris", from Latin "pretium"' },
  PRIDE: { pos: 'noun', definition: 'Deep satisfaction; a group of lions; excessive self-esteem', origin: 'Old English "pryde"' },
  PRIME: { pos: 'adjective/noun', definition: 'Of highest quality; a prime number; the best time', origin: 'Latin "primus" (first)' },
  PROBE: { pos: 'noun/verb', definition: 'A surgical instrument; a spacecraft; to investigate', origin: 'Medieval Latin "proba"' },
  PRONE: { pos: 'adjective', definition: 'Lying face down; likely to suffer from', origin: 'Latin "pronus"' },
  PROOF: { pos: 'noun/adjective', definition: 'Evidence; strength of alcohol; resistant to', origin: 'Old French "prueve"' },
  PROSE: { pos: 'noun', definition: 'Written language not in verse; ordinary writing', origin: 'Latin "prosa"' },
  PROUD: { pos: 'adjective', definition: 'Having high self-esteem; pleased about an achievement', origin: 'Old English "prut"' },
  PROWL: { pos: 'verb/noun', definition: 'To move stealthily; a period of prowling', origin: 'Unknown origin' },
  PROXY: { pos: 'noun', definition: 'One authorized to act for another; a substitute', origin: 'Middle English "procuracy"' },
  PRUNE: { pos: 'noun/verb', definition: 'A dried plum; to trim by cutting away; to remove', origin: 'Old French "prune"' },
  QUEEN: { pos: 'noun', definition: 'A female monarch; the most powerful chess piece', origin: 'Old English "cwen"' },
  QUILL: { pos: 'noun', definition: 'A large feather; a porcupine spine; a writing instrument', origin: 'Middle Low German "quiele"' },
  QUILT: { pos: 'noun/verb', definition: 'A thick padded bed covering; to make a quilt', origin: 'Old French "cuilte"' },
  QUIRK: { pos: 'noun', definition: 'A peculiarity; a strange habit', origin: 'Unknown origin' },
  QUOTA: { pos: 'noun', definition: 'A fixed share or number; a limited quantity allocated', origin: 'Medieval Latin "quota"' },
  RADAR: { pos: 'noun', definition: 'A system for detecting objects using radio waves', origin: 'Acronym: Radio Detection And Ranging' },
  RAINY: { pos: 'adjective', definition: 'Having or characterized by rain', origin: 'Old English "regn"' },
  RANCH: { pos: 'noun/verb', definition: 'A large farm for livestock; to manage a ranch', origin: 'Spanish "rancho"' },
  RANGE: { pos: 'noun/verb', definition: 'The extent of variation; to vary; to travel over', origin: 'Old French "rengier"' },
  RAPID: { pos: 'adjective', definition: 'Happening in a short time; fast', origin: 'Latin "rapidus"' },
  RAISE: { pos: 'verb/noun', definition: 'To lift; to increase; an increase in pay', origin: 'Old Norse "reisa"' },
  REBEL: { pos: 'noun/verb', definition: 'A person who resists authority; to resist authority', origin: 'Old French "rebelle"' },
  REBUT: { pos: 'verb', definition: 'To prove wrong; to refute', origin: 'Old French "rebouter"' },
  REPAY: { pos: 'verb', definition: 'To pay back; to do something in return', origin: 'Old French "repayer"' },
  RIDER: { pos: 'noun', definition: 'A person who rides; an additional clause or condition', origin: 'Old English "ridan"' },
  RIDGE: { pos: 'noun', definition: 'A long narrow hilltop; the top of a roof', origin: 'Old English "hrycg"' },
  RIFLE: { pos: 'noun/verb', definition: 'A firearm; to search through hastily', origin: 'Old French "rifler" (to plunder)' },
  RIGID: { pos: 'adjective', definition: 'Unable to bend or flex; strict; not adaptable', origin: 'Latin "rigidus"' },
  RISKY: { pos: 'adjective', definition: 'Involving a risk; dangerous; uncertain', origin: 'French "risque"' },
  RIVAL: { pos: 'noun/verb', definition: 'A competitor; to be as good as; to compete with', origin: 'Latin "rivalis"' },
  ROAST: { pos: 'verb/noun', definition: 'To cook in an oven; an event at which someone is teased', origin: 'Old French "rostir"' },
  ROGUE: { pos: 'noun/adjective', definition: 'A dishonest person; behaving in a dangerous manner', origin: 'Unknown origin' },
  ROUGH: { pos: 'adjective', definition: 'Having an uneven surface; not gentle; difficult', origin: 'Old English "ruh"' },
  ROUND: { pos: 'adjective/noun', definition: 'Circular; a cycle; a drink bought for others', origin: 'Old French "roond"' },
  ROWDY: { pos: 'adjective/noun', definition: 'Noisy and disorderly; a rowdy person', origin: 'Originally US slang' },
  RULER: { pos: 'noun', definition: 'A person who rules; a measuring instrument', origin: 'Old English "raedan"' },
  SAVOR: { pos: 'verb/noun', definition: 'To enjoy fully; taste or smell of something', origin: 'Old French "savourer"' },
  SCARY: { pos: 'adjective', definition: 'Frightening; causing fear', origin: 'Old Norse "skirra" (to frighten)' },
  SCENT: { pos: 'noun/verb', definition: 'A distinctive pleasant smell; to smell', origin: 'Old French "sentir"' },
  SCOLD: { pos: 'verb/noun', definition: 'To rebuke angrily; a person who scolds', origin: 'Old Norse "skald" (poet, satirist)' },
  SCOPE: { pos: 'noun', definition: 'The extent of an area or subject; opportunity for action', origin: 'Greek "skopos" (target)' },
  SCORE: { pos: 'noun/verb', definition: 'A number of points; to gain points; a piece of music', origin: 'Old Norse "skor"' },
  SCOUT: { pos: 'noun/verb', definition: 'A person sent ahead; to observe and gather information', origin: 'Old French "escouter"' },
  SCOWL: { pos: 'noun/verb', definition: 'An angry expression; to make such an expression', origin: 'Danish "skule"' },
  SCRAM: { pos: 'verb', definition: 'To leave hastily; to go away quickly', origin: 'Origin uncertain' },
  SCRAP: { pos: 'noun/verb', definition: 'A small piece; a fight; to discard', origin: 'Old Norse "skrap"' },
  SCRUB: { pos: 'verb/noun', definition: 'To rub hard to clean; a thorough cleaning; low trees', origin: 'Middle Dutch "schrobben"' },
  SEEDY: { pos: 'adjective', definition: 'Containing seeds; run-down; disreputable', origin: 'Old English "sæd"' },
  SEIZE: { pos: 'verb', definition: 'To take hold of forcibly; to capture; to understand', origin: 'Old French "seisir"' },
  SENSE: { pos: 'noun/verb', definition: 'A faculty by which the body perceives; to detect', origin: 'Latin "sensus"' },
  SERVE: { pos: 'verb/noun', definition: 'To perform service; to provide food; a service in tennis', origin: 'Old French "servir"' },
  SHAFT: { pos: 'noun', definition: 'A long narrow passage; a long handle; an arrow', origin: 'Old English "sceaft"' },
  SHAKE: { pos: 'verb/noun', definition: 'To tremble or vibrate; an act of shaking', origin: 'Old English "scacan"' },
  SHAME: { pos: 'noun/verb', definition: 'A feeling of humiliation; something regrettable; to embarrass', origin: 'Old English "scamu"' },
  SHARD: { pos: 'noun', definition: 'A sharp piece of broken material', origin: 'Old English "sceard"' },
  SHARE: { pos: 'noun/verb', definition: 'A portion; a financial unit; to give portions to', origin: 'Old English "scear"' },
  SHARK: { pos: 'noun', definition: 'A large predatory fish; an unscrupulous person', origin: 'German "Schurke" (scoundrel)' },
  SHAWL: { pos: 'noun', definition: 'A piece of fabric worn around the shoulders', origin: 'Persian "shal"' },
  SHOWY: { pos: 'adjective', definition: 'Ostentatious; making an impressive display', origin: 'Old English "sceawian"' },
  SHRUG: { pos: 'verb/noun', definition: 'To raise and contract the shoulders; such a gesture', origin: 'Unknown origin' },
  SKILL: { pos: 'noun', definition: 'The ability to do something well; expertise', origin: 'Old Norse "skil" (distinction)' },
  SKIMP: { pos: 'verb', definition: 'To use or provide less of something; to be frugal', origin: 'Possibly Scandinavian origin' },
  SLACK: { pos: 'adjective/noun/verb', definition: 'Not tight; not busy; a period of inactivity; to loosen', origin: 'Old English "slæc"' },
  SLANT: { pos: 'noun/verb', definition: 'A sloping direction; to slope; a bias', origin: 'Old Norse "slenta"' },
  SLASH: { pos: 'verb/noun', definition: 'To cut with a sweeping stroke; a long cut', origin: 'Old French "esclachier"' },
  SLAVE: { pos: 'noun', definition: 'A person who is owned by another; a hard worker', origin: 'Medieval Latin "sclavus"' },
  SLEEK: { pos: 'adjective', definition: 'Smooth and glossy; elegant and stylish', origin: 'Old Norse "slikr"' },
  SLEEP: { pos: 'noun/verb', definition: 'A state of rest; to be in this state', origin: 'Old English "slæp"' },
  SLEET: { pos: 'noun/verb', definition: 'A mixture of rain and snow; to fall as sleet', origin: 'Middle English "slete"' },
  SLICK: { pos: 'adjective/noun', definition: 'Smooth and slippery; done in an impressively efficient way', origin: 'Middle English "slikke"' },
  SLIME: { pos: 'noun', definition: 'A moist, soft substance; viscous mud', origin: 'Old English "slim"' },
  SLOPE: { pos: 'noun/verb', definition: 'Ground that is not flat; to be inclined', origin: 'Old English "aslupan"' },
  SLUMP: { pos: 'verb/noun', definition: 'To sit heavily; a period of poor performance', origin: 'Possibly Norwegian "slumpe"' },
  SMASH: { pos: 'verb/noun', definition: 'To break to pieces; a collision; a great success', origin: 'Possibly blend of "smack" and "mash"' },
  SMEAR: { pos: 'verb/noun', definition: 'To spread a sticky substance; a mark made this way', origin: 'Old English "smerian"' },
  SNACK: { pos: 'noun', definition: 'A small amount of food eaten between meals', origin: 'Middle Dutch "snacken"' },
  SNAKE: { pos: 'noun/verb', definition: 'A legless reptile; to move in a winding path', origin: 'Old English "snaca"' },
  SNARE: { pos: 'noun/verb', definition: 'A trap; to catch in a trap; a drum component', origin: 'Old English "sneare"' },
  SNEAK: { pos: 'verb/noun', definition: 'To move furtively; a contemptible person', origin: 'Old English "snican"' },
  SNEER: { pos: 'verb/noun', definition: 'To smile scornfully; a scornful expression', origin: 'Possibly Low German "snarren"' },
  SNIFF: { pos: 'verb/noun', definition: 'To draw air audibly; an act of sniffing', origin: 'Middle English "sniffen"' },
  SNORE: { pos: 'verb/noun', definition: 'To breathe noisily during sleep; the sound of snoring', origin: 'Imitative' },
  SNOUT: { pos: 'noun', definition: 'The projecting nose and mouth of an animal', origin: 'Middle Dutch "snute"' },
  SOLAR: { pos: 'adjective', definition: 'Relating to or determined by the sun', origin: 'Latin "solaris"' },
  SOLVE: { pos: 'verb', definition: 'To find an answer to a problem', origin: 'Latin "solvere"' },
  SORRY: { pos: 'adjective', definition: 'Feeling distress; feeling regret; wretched', origin: 'Old English "sarig"' },
  SOUTH: { pos: 'noun/adjective', definition: 'The direction opposite north; the southern part', origin: 'Old English "suth"' },
  SPARE: { pos: 'adjective/noun/verb', definition: 'Extra; to refrain from harming; a spare part', origin: 'Old English "sparian"' },
  SPARK: { pos: 'noun/verb', definition: 'A small fiery particle; to cause to start; to stimulate', origin: 'Old English "spearca"' },
  SPAWN: { pos: 'verb/noun', definition: 'To produce offspring; eggs of fish or frogs', origin: 'Old French "espandre"' },
  SPECK: { pos: 'noun', definition: 'A tiny spot; a small particle', origin: 'Old English "specca"' },
  SPEND: { pos: 'verb', definition: 'To pay out money; to pass time; to use up', origin: 'Old English "spendan"' },
  SPICE: { pos: 'noun/verb', definition: 'An aromatic substance; to add spice to', origin: 'Old French "espice"' },
  SPIKE: { pos: 'noun/verb', definition: 'A thin pointed piece; to pierce with a spike', origin: 'Old Norse "spikr"' },
  SPILL: { pos: 'verb/noun', definition: 'To flow out accidentally; an act of spilling', origin: 'Old English "spillan"' },
  SPINE: { pos: 'noun', definition: 'The backbone; a sharp pointed projection; a book\'s edge', origin: 'Latin "spina"' },
  SPITE: { pos: 'noun/verb', definition: 'Desire to hurt; in spite of; to annoy deliberately', origin: 'Old French "despit"' },
  SPOKE: { pos: 'noun/verb', definition: 'A rod connecting wheel hub to rim; past tense of speak', origin: 'Old English "spaca"' },
  SPOOK: { pos: 'noun/verb', definition: 'A ghost; a spy; to frighten', origin: 'Dutch "spook"' },
  SPOON: { pos: 'noun/verb', definition: 'A utensil for eating liquid food; to take with a spoon', origin: 'Old English "spon"' },
  SPORE: { pos: 'noun', definition: 'A reproductive unit of fungi, plants, or microorganisms', origin: 'Greek "spora" (seed)' },
  SPORT: { pos: 'noun/verb', definition: 'An athletic activity; to wear or display', origin: 'Old French "desport"' },
  SPOUT: { pos: 'noun/verb', definition: 'A tube for pouring liquid; to pour out rapidly', origin: 'Middle Dutch "sputen"' },
  SPRAY: { pos: 'noun/verb', definition: 'Liquid in tiny drops; to apply as a spray', origin: 'Middle Dutch "sprayen"' },
  SPUNK: { pos: 'noun', definition: 'Courage; tinder; spirit', origin: 'Irish/Scottish Gaelic "spong" (tinder)' },
  STAIN: { pos: 'noun/verb', definition: 'A mark of discoloration; to make a stain on', origin: 'Old Norse "steinn" (stone paint)' },
  STAKE: { pos: 'noun/verb', definition: 'A pointed stick; something wagered; to mark boundaries', origin: 'Old English "staca"' },
  STALE: { pos: 'adjective/verb', definition: 'No longer fresh; to make or become stale', origin: 'Old French "estale" (standing)' },
  STALK: { pos: 'noun/verb', definition: 'The stem of a plant; to pursue; to walk stiffly', origin: 'Old English "stealc"' },
  STAMP: { pos: 'verb/noun', definition: 'To bring foot down heavily; a mark made by pressing', origin: 'Old English "stempan"' },
  STAND: { pos: 'verb/noun', definition: 'To be on one\'s feet; a structure for holding things', origin: 'Old English "standan"' },
  STARK: { pos: 'adjective', definition: 'Severe; complete; desolate; strong and rigid', origin: 'Old English "stearc"' },
  STASH: { pos: 'verb/noun', definition: 'To store secretly; a secret store', origin: 'Origin uncertain' },
  STAVE: { pos: 'noun/verb', definition: 'A wooden strip; a verse; to break a hole in', origin: 'Old English "stæf"' },
  STEAL: { pos: 'verb', definition: 'To take without permission; to move quietly', origin: 'Old English "stelan"' },
  STEAM: { pos: 'noun/verb', definition: 'Water vapor; to cook with steam; to move by steam power', origin: 'Old English "steam"' },
  STEEL: { pos: 'noun/verb', definition: 'A hard strong metal alloy; to mentally prepare oneself', origin: 'Old English "style"' },
  STERN: { pos: 'adjective/noun', definition: 'Strict; severe; the rear of a ship', origin: 'Old Norse "stjorn"' },
  STIFF: { pos: 'adjective', definition: 'Not easily bent; formal; strong (of a drink)', origin: 'Old English "stif"' },
  STILL: { pos: 'adjective/adverb', definition: 'Not moving; up to and including now; even so', origin: 'Old English "stille"' },
  STING: { pos: 'verb/noun', definition: 'To wound with a stinger; a painful wound; a swindle', origin: 'Old English "stingan"' },
  STINK: { pos: 'verb/noun', definition: 'To have a strong unpleasant smell; such a smell', origin: 'Old English "stincan"' },
  STOCK: { pos: 'noun/verb', definition: 'Supply kept for use; a company\'s shares; to supply', origin: 'Old English "stocc" (trunk)' },
  STOMP: { pos: 'verb/noun', definition: 'To tread heavily; a stamping action', origin: 'Variant of "stamp"' },
  STORE: { pos: 'noun/verb', definition: 'A place where goods are sold; to keep for future use', origin: 'Old French "estorer"' },
  STORM: { pos: 'noun/verb', definition: 'A violent weather event; to move angrily', origin: 'Old English "storm"' },
  STORY: { pos: 'noun', definition: 'An account of events; a floor of a building', origin: 'Latin "historia"' },
  STRAP: { pos: 'noun/verb', definition: 'A strip of material; to fasten with a strap', origin: 'Middle Dutch "stroppe"' },
  STRAY: { pos: 'verb/adjective', definition: 'To move away from a group; a lost animal; random', origin: 'Old French "estraier"' },
  STRIP: { pos: 'verb/noun', definition: 'To remove covering; a long narrow piece', origin: 'Old English "strypan"' },
  STRUT: { pos: 'verb/noun', definition: 'To walk with pride; a structural support', origin: 'Old English "strutian"' },
  STUCK: { pos: 'adjective', definition: 'Past tense of stick; unable to move or progress', origin: 'Old English "stician"' },
  STUDY: { pos: 'noun/verb', definition: 'The action of examining; a room for reading; to learn', origin: 'Old French "estudie"' },
  STUMP: { pos: 'noun/verb', definition: 'A tree base left after cutting; to baffle; to walk heavily', origin: 'Middle Low German "stump"' },
  STUNG: { pos: 'verb', definition: 'Past tense of sting; affected by a sting', origin: 'Old English "stingan"' },
  STUNK: { pos: 'verb', definition: 'Past tense and past participle of stink', origin: 'Old English "stincan"' },
  STYLE: { pos: 'noun', definition: 'A manner of doing; elegance; a fashion', origin: 'Latin "stilus" (writing instrument)' },
  SUGAR: { pos: 'noun', definition: 'A sweet crystalline substance; to coat with sugar', origin: 'Old French "sucre"' },
  SUITE: { pos: 'noun', definition: 'A set of rooms; a set of matching furniture; a musical form', origin: 'French "suite" (follow)' },
  SUNNY: { pos: 'adjective', definition: 'Bright with sunlight; cheerful and bright in temperament', origin: 'Old English "sunne"' },
  SUPER: { pos: 'adjective/adverb', definition: 'Extremely good; to a great degree; beyond normal', origin: 'Latin "super" (above)' },
  SURGE: { pos: 'verb/noun', definition: 'To move forward suddenly; a sudden powerful rush', origin: 'Old French "surgir"' },
  SWAMP: { pos: 'noun/verb', definition: 'Waterlogged ground; to overwhelm with too much', origin: 'Low German "swamp"' },
  SWEAR: { pos: 'verb', definition: 'To make a solemn statement; to use offensive language', origin: 'Old English "swerian"' },
  SWEEP: { pos: 'verb/noun', definition: 'To clean with a broom; a long curved movement', origin: 'Old English "swapan"' },
  SWEPT: { pos: 'verb', definition: 'Past tense of sweep; cleaned with a broom', origin: 'Old English "swapan"' },
  SWIRL: { pos: 'verb/noun', definition: 'To move in a whirling pattern; a whirling motion', origin: 'Low German "swirlen"' },
  SWING: { pos: 'verb/noun', definition: 'To move to and fro; a seat hung to swing', origin: 'Old English "swingan"' },
  SWUNG: { pos: 'verb', definition: 'Past tense of swing', origin: 'Old English "swingan"' },
  TABOO: { pos: 'noun/adjective', definition: 'A social prohibition; forbidden by social custom', origin: 'Tongan "tabu" (sacred)' },
  TAKEN: { pos: 'adjective', definition: 'Past participle of take; already occupied; charmed by', origin: 'Old English "tacan"' },
  TAUNT: { pos: 'verb/noun', definition: 'To provoke with insults; a provocative remark', origin: 'Old French "tanter"' },
  TEPID: { pos: 'adjective', definition: 'Lukewarm; showing little enthusiasm', origin: 'Latin "tepidus"' },
  THICK: { pos: 'adjective', definition: 'Of great distance from one side to the other; dense', origin: 'Old English "thicce"' },
  THIEF: { pos: 'noun', definition: 'A person who steals', origin: 'Old English "theof"' },
  THING: { pos: 'noun', definition: 'An object; a matter or subject; an event', origin: 'Old English "thing"' },
  THINK: { pos: 'verb', definition: 'To have a particular opinion; to use the mind', origin: 'Old English "thencan"' },
  THORN: { pos: 'noun', definition: 'A sharp pointed projection; something causing pain', origin: 'Old English "thorn"' },
  THREE: { pos: 'numeral', definition: 'The number 3; one more than two', origin: 'Old English "threo"' },
  TIGER: { pos: 'noun', definition: 'A large striped wild cat; a fierce person', origin: 'Greek "tigris"' },
  TINGE: { pos: 'noun/verb', definition: 'A small trace of color or feeling; to color slightly', origin: 'Latin "tingere" (to dip)' },
  TIRED: { pos: 'adjective', definition: 'Feeling the need for sleep; bored with; overused', origin: 'Old English "teorian"' },
  TOAST: { pos: 'noun/verb', definition: 'Browned bread; a tribute; to brown bread; to honor', origin: 'Old French "toster"' },
  TOKEN: { pos: 'noun/adjective', definition: 'A symbol; a metal disc; serving as a symbolic gesture', origin: 'Old English "tacen"' },
  TOPAZ: { pos: 'noun', definition: 'A precious stone, typically yellow; a yellow-green hue', origin: 'Greek "topazos"' },
  TORCH: { pos: 'noun/verb', definition: 'A burning stick; a flashlight; to set fire to', origin: 'Old French "torche"' },
  TOTEM: { pos: 'noun', definition: 'A natural object serving as the emblem of a clan', origin: 'Ojibwe "ototeman" (his kinship group)' },
  TOWEL: { pos: 'noun/verb', definition: 'A cloth for drying; to dry with a towel', origin: 'Old French "toaille"' },
  TOWER: { pos: 'noun/verb', definition: 'A tall narrow structure; to rise to a great height', origin: 'Old English "torr"' },
  TOXIC: { pos: 'adjective', definition: 'Poisonous; very harmful; very unpleasant', origin: 'Greek "toxikon" (arrow poison)' },
  TRACK: { pos: 'noun/verb', definition: 'A path; a mark left by something; to follow', origin: 'Old French "trac"' },
  TRADE: { pos: 'noun/verb', definition: 'The buying and selling of goods; to buy and sell', origin: 'Middle Low German "trade"' },
  TRAIL: { pos: 'noun/verb', definition: 'A path through nature; to follow behind', origin: 'Old French "trailler"' },
  TRAIN: { pos: 'noun/verb', definition: 'A series of connected railway cars; to teach; to exercise', origin: 'Old French "trainer"' },
  TRAIT: { pos: 'noun', definition: 'A distinguishing quality or characteristic', origin: 'French "trait", from Latin "tractus"' },
  TRAMP: { pos: 'noun/verb', definition: 'A homeless wanderer; to walk heavily', origin: 'Middle Low German "trampen"' },
  TRASH: { pos: 'noun/verb', definition: 'Waste material; something worthless; to wreck', origin: 'Old Norse "tros"' },
  TRAWL: { pos: 'verb/noun', definition: 'To fish with a trawl net; to search thoroughly', origin: 'Dutch "trawl"' },
  TREND: { pos: 'noun/verb', definition: 'A general direction; a fashion; to move in a direction', origin: 'Old English "trendan"' },
  TRIAL: { pos: 'noun', definition: 'A formal examination of evidence; a test; an ordeal', origin: 'Old French "trial"' },
  TRIBE: { pos: 'noun', definition: 'A social group; a distinct group of people', origin: 'Latin "tribus"' },
  TRICK: { pos: 'noun/verb', definition: 'A cunning action; to deceive; a skill', origin: 'Old French "trichier"' },
  TRIED: { pos: 'adjective', definition: 'Tested and proved reliable; past tense of try', origin: 'Old French "trier"' },
  TROLL: { pos: 'noun/verb', definition: 'A mythological creature; to fish by trailing a line', origin: 'Old Norse "troll"' },
  TROUT: { pos: 'noun', definition: 'A fish related to salmon, typically freshwater', origin: 'Old English "truht"' },
  TROVE: { pos: 'noun', definition: 'A store of valuable things', origin: 'Old French "trover" (to find)' },
  TRUCE: { pos: 'noun', definition: 'An agreement to stop fighting temporarily', origin: 'Old English "treow" (faith, treaty)' },
  TRUNK: { pos: 'noun', definition: 'The main stem of a tree; a large case; an elephant\'s nose', origin: 'Old French "tronc"' },
  TRUST: { pos: 'noun/verb', definition: 'Firm belief in reliability; to believe in the honesty of', origin: 'Old Norse "traust"' },
  TRUTH: { pos: 'noun', definition: 'The quality of being true; a fact that is accepted as true', origin: 'Old English "treowth"' },
  TUBER: { pos: 'noun', definition: 'A thick underground stem with stored nutrients (like a potato)', origin: 'Latin "tuber" (lump)' },
  TULIP: { pos: 'noun', definition: 'A spring-flowering bulbous plant', origin: 'Turkish "tulbend" (turban)' },
  TUMOR: { pos: 'noun', definition: 'An abnormal growth of tissue in the body', origin: 'Latin "tumor"' },
  TUNER: { pos: 'noun', definition: 'A device that tunes; a person who tunes instruments', origin: 'Old French "toner"' },
  TURBO: { pos: 'noun/adjective', definition: 'A turbine; driven by a turbocharger; very fast', origin: 'Latin "turbo" (spinning top)' },
  TWANG: { pos: 'noun/verb', definition: 'A strong ringing sound; to make this sound', origin: 'Imitative' },
  TWICE: { pos: 'adverb', definition: 'Two times; on two occasions; to double degree', origin: 'Old English "twiges"' },
  TWILL: { pos: 'noun', definition: 'A fabric with diagonal parallel ridges', origin: 'Old English "twili"' },
  TWINE: { pos: 'noun/verb', definition: 'Strong thread; to wind or coil around', origin: 'Old English "twin" (double thread)' },
  TWIST: { pos: 'verb/noun', definition: 'To turn one end in one direction; a turning movement', origin: 'Old English "twist" (divided object)' },
  ULTRA: { pos: 'adjective/prefix', definition: 'Extreme; going beyond; to an extreme degree', origin: 'Latin "ultra" (beyond)' },
  UNDER: { pos: 'preposition', definition: 'Extending or directly below; subject to', origin: 'Old English "under"' },
  UNDUE: { pos: 'adjective', definition: 'Exceeding proper limits; too great; not appropriate', origin: 'Latin "indebitus"' },
  UNTIL: { pos: 'preposition/conjunction', definition: 'Up to the time that; as far as', origin: 'Old Norse "und til"' },
  USHER: { pos: 'noun/verb', definition: 'A person who shows people to their seats; to guide', origin: 'Old French "ussier"' },
  USUAL: { pos: 'adjective', definition: 'Habitually occurring; normal', origin: 'Latin "usualis"' },
  UTTER: { pos: 'adjective/verb', definition: 'Complete; absolute; to speak or make a sound', origin: 'Old English "utor" (outer)' },
  VALOR: { pos: 'noun', definition: 'Great courage in the face of danger; bravery', origin: 'Old French "valour"' },
  VALUE: { pos: 'noun/verb', definition: 'The worth of something; to consider important', origin: 'Old French "value"' },
  VALVE: { pos: 'noun', definition: 'A device controlling flow; a hollow shell; a vacuum tube', origin: 'Latin "valva" (leaf of a door)' },
  VAPOR: { pos: 'noun', definition: 'A substance in the gas phase; moisture in the air', origin: 'Latin "vapor"' },
  VENOM: { pos: 'noun', definition: 'Poison secreted by snakes; spite; malice', origin: 'Old French "venin"' },
  VERGE: { pos: 'noun/verb', definition: 'The edge of something; to be on the brink of', origin: 'Old French "verge"' },
  VEXED: { pos: 'adjective', definition: 'Annoyed; frustrated; difficult and much discussed', origin: 'Latin "vexare"' },
  VISOR: { pos: 'noun', definition: 'A peak on a cap; the part of a helmet over the face', origin: 'Old French "visiere"' },
  VITAL: { pos: 'adjective', definition: 'Essential; absolutely necessary; full of life', origin: 'Latin "vitalis"' },
  VOCAL: { pos: 'adjective', definition: 'Relating to voice; expressing opinions freely', origin: 'Latin "vocalis"' },
  VOMIT: { pos: 'verb/noun', definition: 'To eject stomach contents through the mouth', origin: 'Latin "vomere"' },
  VOTER: { pos: 'noun', definition: 'A person who votes', origin: 'Latin "votum" (vow)' },
  WAIST: { pos: 'noun', definition: 'The part of the body between ribs and hips', origin: 'Old English "wæst" (growth)' },
  WALTZ: { pos: 'noun/verb', definition: 'A ballroom dance; to dance a waltz; to move easily', origin: 'German "Walzer"' },
  WASTE: { pos: 'noun/verb', definition: 'Material not needed; to use carelessly; to become weaker', origin: 'Old French "wast"' },
  WATCH: { pos: 'verb/noun', definition: 'To look attentively; a timepiece; a period of watching', origin: 'Old English "wæccan"' },
  WATER: { pos: 'noun/verb', definition: 'A colorless liquid; to pour water on', origin: 'Old English "wæter"' },
  WEARY: { pos: 'adjective/verb', definition: 'Tired; to make or become tired', origin: 'Old English "werig"' },
  WEAVE: { pos: 'verb/noun', definition: 'To interlace threads; a pattern produced by weaving', origin: 'Old English "wefan"' },
  WEDGE: { pos: 'noun/verb', definition: 'A triangular tool; to squeeze tightly', origin: 'Old English "wecg"' },
  WEIRD: { pos: 'adjective', definition: 'Strikingly odd; supernatural; unearthly', origin: 'Old English "wyrd" (fate)' },
  WHEAT: { pos: 'noun', definition: 'A cereal grain widely cultivated for its seed', origin: 'Old English "hwæte"' },
  WHEEL: { pos: 'noun/verb', definition: 'A circular frame turning on an axle; to push on wheels', origin: 'Old English "hweol"' },
  WHERE: { pos: 'adverb', definition: 'In, at, or to what place; in the circumstances', origin: 'Old English "hwær"' },
  WHICH: { pos: 'pronoun/adjective', definition: 'Asking for identification; used to refer to', origin: 'Old English "hwilc"' },
  WHILE: { pos: 'conjunction/noun', definition: 'During the time that; a period of time', origin: 'Old English "hwil"' },
  WHIRL: { pos: 'verb/noun', definition: 'To move rapidly in circles; a rapid circular movement', origin: 'Old Norse "hvirfla"' },
  WHISK: { pos: 'verb/noun', definition: 'To move quickly; to beat eggs; a utensil for whisking', origin: 'Old Norse "visk"' },
  WIDEN: { pos: 'verb', definition: 'To become or make wider', origin: 'Old English "wid"' },
  WINDY: { pos: 'adjective', definition: 'Characterized by strong winds; using many words', origin: 'Old English "windige"' },
  WITCH: { pos: 'noun', definition: 'A person practicing magic; a woman with supposed magical powers', origin: 'Old English "wicce"' },
  WITTY: { pos: 'adjective', definition: 'Showing or characterized by quick intelligence; clever', origin: 'Old English "wittig"' },
  WOODY: { pos: 'adjective', definition: 'Covered with trees; resembling wood; tough', origin: 'Old English "wudu"' },
  WORSE: { pos: 'adjective', definition: 'More bad; less well; more severe', origin: 'Old English "wyrsa"' },
  WORST: { pos: 'adjective', definition: 'Most bad; most severe; least good', origin: 'Old English "wyrst"' },
  WRIST: { pos: 'noun', definition: 'The joint connecting the hand and forearm', origin: 'Old English "wrist"' },
  WRONG: { pos: 'adjective/noun/verb', definition: 'Not correct; an unjust act; to act unjustly toward', origin: 'Old Norse "rangr"' },
  WROTE: { pos: 'verb', definition: 'Past tense of write', origin: 'Old English "writan"' },
  YACHT: { pos: 'noun/verb', definition: 'A medium-sized sailboat; to sail a yacht', origin: 'Dutch "jacht"' },
  YEARN: { pos: 'verb', definition: 'To have a strong desire; to feel a longing for', origin: 'Old English "giernan"' },
  YEAST: { pos: 'noun', definition: 'A microscopic fungus used in baking and brewing', origin: 'Old English "gist"' },
  YIELD: { pos: 'verb/noun', definition: 'To produce; to give way; the amount produced', origin: 'Old English "gieldan"' },
  ZESTY: { pos: 'adjective', definition: 'Having a strong pleasant flavor; spirited and lively', origin: 'French "zeste" (orange peel)' },
}

// Generate stub for any answer not in curated set
const etymologyData: Record<string, EtymologyEntry> = {}

for (const word of answers) {
  const upperWord = word.toUpperCase()
  if (curatedEtymology[upperWord]) {
    etymologyData[upperWord] = curatedEtymology[upperWord]
  } else {
    // Generate a basic stub — real etymology to be sourced for production
    etymologyData[upperWord] = {
      pos: 'noun',
      definition: `A five-letter English word.`,
      origin: 'English',
    }
  }
}

const etymologyCoverage = answers.filter(w => curatedEtymology[w.toUpperCase()]).length
console.log(
  `[compile-data] etymology: ${Object.keys(etymologyData).length} entries ` +
    `(${etymologyCoverage} curated, ${answers.length - etymologyCoverage} stubs)`,
)

// ─── Write JSON files ─────────────────────────────────────────────────────────

mkdirSync(dataDir, { recursive: true })

writeFileSync(resolve(dataDir, 'valid-words.json'), JSON.stringify(allValid, null, 2))
console.log(`[compile-data] ✅ Wrote src/data/valid-words.json (${allValid.length} words)`)

writeFileSync(resolve(dataDir, 'answers.json'), JSON.stringify(answers, null, 2))
console.log(`[compile-data] ✅ Wrote src/data/answers.json (${answers.length} words)`)

writeFileSync(resolve(dataDir, 'etymology.json'), JSON.stringify(etymologyData, null, 2))
console.log(`[compile-data] ✅ Wrote src/data/etymology.json (${Object.keys(etymologyData).length} entries)`)

console.log('[compile-data] ✅ Data pipeline complete.')
